### ISSUE TITLE
请问静态文件css jpg等ciswoole是怎么处理的?

### ISSUE THREAD

**Issue by wizarot** [smalleyes/ciswoole#1]
请问css ,jpg等是如何处理的?
我直接跑server显示css,jpg,ico等文件没有获取到?
是需要nginx做代理,还是我哪里设置不对呢.

**Comment by toxmc** [comment]
css,jpg通过nginx处理，php通过nginx转发给swoole_http_server处理。可以查看ciswoole.conf，nginx配置文件。

**Comment by wizarot** [comment]
那么如果使用swoole framework 那样增加发送静态文件的功能,是否合适呢?
会对性能有什么影响吗?

**Comment by toxmc** [comment]
nginx的强项就是处理静态文件，现在swoole_http_server还没有达到nginx处理静态文件的速度，要集成也是可以的，就是了。
